opszero/terraform-aws-kubespot

.gitignore
Makefile
image.json

AWS Marketplace Image

---

ami/ossec.sh
image.json

GPG Check for OSSEC

---

.gitignore
eks/ami.tf
eks/bastion.tf
eks/inputs.tf
eks/kubernetes.tf
eks/vpn.tf
packer/ami/cloudwatch.sh
packer/image.json

Example triggers are in the slack. Should they be part of the readme? 
Making another branch for cloudwatch and another for the LogDNA Daemonset.

VPN + Bastion LogDNA

---

gcp/outputs.tf

Need the gcp module to output the database instance name for use in other common modules

gcp outputs for database

---

gcp/outputs.tf

Fixed where the output was not accurate

fixed output count index

---

eks/bastion.tf
eks/fargate.tf
eks/iam.tf
eks/inputs.tf
eks/kubernetes.tf

AWS Fargate

---

eks/ami.tf
eks/inputs.tf
eks/main.tf

- Move the EKS Image and Encrypted Launch
- Moved Performance Conf
The goal is to remove the custom images we have.

Migrated to using the EKS Node image

---

eks/efs.tf
eks/helm-efs.tf
eks/helm.tf
eks/iam.tf
eks/variables.tf

https://docs.aws.amazon.com/eks/latest/userguide/efs-csi.html

EFS > IAM role for eks service account and efs helm deployment

---

eks/cluster-autoscaler.tf
eks/cluster_autoscaler.tf
eks/iam.tf
eks/variables.tf

Already added tags in place in autoscaling group
k8s.io/cluster-autoscaler/&lt;cluster-name&gt; | owned
-- | --
k8s.io/cluster-autoscaler/enabled | TRUE

Add cluster autoscaler and helm deployment

---

eks/iam.tf
eks/variables.tf

EKS node policy move to variable

---

eks/fargate.tf
eks/variables.tf

Fargate > Name selector fix

---

output.tf
private_subnet.tf

Expose the nat_gateway from the kubespot module to consumers

Output module nat_gateway_id

---

variables.tf

update helm chart version

---

ami.tf
bastion.tf
variables.tf

remove foxpass

---

bastion.tf
variables.tf

remove logdna from aws-kubespot

---

variables.tf

update helm chart versions

---

variables.tf

update karpenter version

---

node.tf
variables.tf

update node group to use spot instance

---

variables.tf

update helm versions

---

variables.tf

update karpenter and csi store helm charts version

---

variables.tf

update helm charts version

---

sql.tf
variables.tf

add sql_peformance_insights_enabled

---

karpenter.tf
sql.tf
variables.tf

enable rds IAM auth

---

variables.tf

update helm charts

---

private_subnet.tf
variables.tf

Rename enable_nat to nat_enabled 

---

.gitignore
examples/eks/main.tf
kubernetes.tf

adding dynamicly rbac users

---

aws_csi_secrets_store.tf
cluster.tf
variables.tf

resolve deprecations

---

variables.tf

Updated the karpenter_version to v0.32.2 as the v0.32.1 is not longer able to be pulled down.

Update karpenter_version to v0.32.2

---

efs.tf
karpenter.tf
variables.tf

Disable aws profile

---

node_groups.tf

Hoists taints block of the aws_eks_node_group as a variable

---

.github/workflows/tfsec.yml
metrics.tf
node_groups.tf

UserData for Custom Node Groups and SOC2 Metrics

---

.github/workflows/tfsec.yml
metrics.tf
node_groups.tf

Add labels to Node Groups

---

node.tf
node_groups.tf

Enable IMDSv2

---

node.tf
node_groups.tf

Fix metadata

---

cluster.tf
kubernetes.tf
variables.tf

Add limit to iam

---

karpenter.tf

Fix karpenter iam

---

cluster.tf
examples/eks/main.tf
iam.tf
metrics_server.tf
node.tf
node_groups.tf
variables.tf

Closes https://github.com/opszero/terraform-aws-kubespot/issues/402

adding depends on matrix and enable s3_csi_driver

---

README.md
outputs.tf

Added aws_iam_openid_connect_provider.cluster.arn to outputs.tf

---

aws_csi_secrets_store.tf

Enable syncSecret

---

aws_csi_secrets_store.tf
examples/eks/main.tf
locals.tf

Fix secrets

---

aws_csi_secrets_store.tf

apply csi for all namspaces

---

cluster.tf
examples/eks/main.tf
node_role.tf
variables.tf

update eks_auto condition and update cloudwath addons

---

karpenter.tf

update metadataOptions in node class

---

node_groups.tf

Add AMI Types to Custom Node Groups

---

node_groups.tf

Fix Version update

---

node_groups.tf

Add user data to AMIs

---

metrics.tf

update comparison_operator argument

---

node_groups.tf

enable varble for root volume

---

karpenter.tf

Reverts opszero/terraform-aws-kubespot#477

Revert "Revert "Bump terraform-aws-modules/eks/aws from 20.37.1 to 21.0.4""

---

helm.tf
karpenter.tf

Karpenter upgrade
